### ISSUE TITLE
TOKEN

### ISSUE THREAD

**Issue by mateja82** [br4in3x/golang-cognito-example#1]
Hey, this is some very solid work, I'm very surprised it seems a bit abandoned... 

I'm a bit confused about the way Tokens are handled, why exactly do you need to insert a token on login page in order to refresh it?

**Comment by max-pv** [comment]
@mateja82 Hello! 

I know this is a very late response, sorry about that - I missed the notification. You probably already found an answer to your question, but anyway, here is a short explanation:

The way authentication works is through tokens. A token denotes your session-id in the AWS Cognito system, so once you are authenticated, there is a session for you created, and you've been given a token that identifies it. 

But the session has a definite span of life, so after some time, your session expires. So does your token. And that means that you're no longer authenticated since there is no session for you, you would have to log in again, which would be a very poor experience (you either have to store user credentials in memory or force user to enter them again). This is where refresh token comes into play. 

With the refresh token, you can elongate your session in AWS Cognito programmatically and safely. In order to elongate the session in AWS Cognito, you're only required to pass a refresh token and set auth flow to "REFRESH_TOKEN_AUTH" (which is done implicitly in my example). As a result, your session would be elongated and you'll receive a new access token and a refresh token.

**Comment by mateja82** [comment]
Thanks so much for the response. I know what a refresh token is, my question was more about why there's a field for you to manually copy and paste the refresh token.

BTW, an amazing job, this is the best implementation of login and registering in Go I've found on the web, thanks for that!!!

**Comment by max-pv** [comment]
Thanks! :) 

Okay, so on the login page you can enter a refresh token manually because it's supposed to demonstrate that the session can be elongated with a refresh token alone (without username/password). This is more of a synthetic example because this authorization request with refresh token supposed to happen programmatically. 

So in real life, this would never be needed. I added it for the sake of completeness.

**Comment by max-pv** [comment]
Since the question is answered, I'm closing this issue.
