### ISSUE TITLE
It's not necessary to disable client hash

### ISSUE THREAD

**Issue by mcharytoniuk** [br4in3x/golang-cognito-example#3]
I think it would be ok to mention that it's not actually necessary to disable client secret hash. I wrote a small blog post about it:
https://dev.to/mcharytoniuk/using-aws-cognito-app-client-secret-hash-with-go-8ld

Are you open to include it in your repo?

**Comment by max-pv** [comment]
@mcharytoniuk That would be great! But in order to keep the code as basic and simple as possible (because this repo is just an example to give an idea of how to make Cognito work in a small web-app), I think the generation of the secret hash should be isolated into a separate function, with extensive documentation.

Now, would you be open to creating a PR?

P.S. Awesome post, man. It will save time for many people, thanks for sharing.

**Comment by mcharytoniuk** [comment]
@br4in3x sure, I can create a PR with a separate function that creates secret hash and keeps everything documented in comments and include it in the `login.go` file as an optional parameter. Does this sound ok?

**Comment by max-pv** [comment]
@mcharytoniuk I think that function can live in the same `login.go` file and be called right in the body of [App.Login](https://github.com/br4in3x/golang-cognito-example/blob/330427a4330926aff829f4e6345c1fb389043a2a/app/login.go#L16) function. In my opinion, it would make it easier to understand, since the function would be used only in one spot. Therefore, an optional parameter is also not required.

But please feel free to decide how you want to implement the change, I'm happy that you're making a contribution :smile:

**Comment by max-pv** [comment]
@mcharytoniuk your PR #4 is merged. Feel free to close this issue if you have no further additions to this topic. Thanks!

**Comment by mcharytoniuk** [comment]
@br4in3x Thanks! I am glad I could contribute.
